### ISSUE TITLE
how to use dockerfiles for dolphin emulator

### ISSUE THREAD

**Issue by jpcapone** [andrewmackrodt/dockerfiles#15]
i figured cloning the https://github.com/andrewmackrodt/dockerfiles was the only way to grab the files for the dolphin emulator.  At this point I am unsure of how to proceed.  The emulator yml file does not expose any ports so i wouldn't know how to connect to it once its up and running.  I can fumble through adding the games via mount points but before I do that I need to understand how to use the emulator.  Just for the record I already have an nvidia gpu passed through the docker host so i am looking for direction in regards to using the dolphin emulator.  Any suggestions would be appreciated, thanks!!
*** I figured out that i need to run Make (even though i have no idea what to do after that lol) but I get the error below:
[2022-28-06 03:10:55] dockermax.FATAL: no build.properties file(s)
make[1]: *** [../Makefile.mk:16: do-build] Error 255
make[1]: Leaving directory '/var/lib/docker/volumes/dolphin/dockerfiles/php'
make: *** [Makefile:3: build] Error 2

Please advise.

**Comment by andrewmackrodt** [comment]
@jpcapone the X11 based images in this repository rely on the hosts X11 installation so no port is exposed to provide, for example, a VNC connection.

**If you want to build your own dolphin image using the provided `Dockerfile`**:
```sh
git clone https://github.com/andrewmackrodt/dockerfiles.git
cd dockerfiles/dolphin-emu-x11
./configure
make
```

However, the configure script will end up pulling the latest image from Dockerhub, so you can follow the instructions from https://github.com/andrewmackrodt/dockerfiles/tree/master/dolphin-emu-x11#docker to get running without having to build your own image. Images are built nightly and build logs are available at https://jenkins.mackrodt.io/job/dockerfiles/job/dolphin-emu-x11/.

The instructions from the README linked above will create a container called `dolphin-emu` which you can then start with `docker start dolphin-emu`; if you have an nvidia GPU, the first start may appear to not do anything for some time while the container tries to install a matching driver to what is available on the host, you can inspect the log output with `docker logs -f dolphin-emu`.

Alternatively, you can copy the `docker-compose.yml` file and then use `docker-compose up` if you have docker compose installed.

Lastly, if you are using nvidia-docker, rather than relying on the containers ability to try and match the driver version with that on the host, you can set the relevant configuration, e.g.

```yaml
---
version: "2.1"

services:
  dolphin-emu:
    image: andrewmackrodt/dolphin-emu-x11
    network_mode: host
    runtime: nvidia
    security_opt:
      - apparmor:unconfined
    shm_size: 128M
    devices:
      - /dev/input
      - /dev/snd
    environment:
      # host UID/GID mapping
      - PUID=${UID:-1000}
      - PGID=${UID:-1000}
      # nvidia
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_SKIP_DOWNLOAD=1
      - NVIDIA_VISIBLE_DEVICES=all
      # x11
      - DISPLAY=unix$DISPLAY
    volumes:
      # x11
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # pulseaudio
      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse:ro
      - $HOME/.config/pulse:/home/ubuntu/.config/pulse:ro
      # dbus
      - /run/user/${UID:-1000}/bus:/run/user/${UID:-1000}/bus:ro
      - /run/dbus:/run/dbus:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      # timezone (optional)
      - /etc/localtime:/etc/localtime:ro
      # dolphin-emu
      - $HOME/.dolphin-emu/Config:/config
      - $HOME/.dolphin-emu:/data
      - $HOME/Games/GameCube:/gc:ro
      - $HOME/Games/Wii:/wii:ro
```
